services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    env_file:
      - .env
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    ports:
      - 61209:61209
      - 61208:61208
    environment:
      - "GLANCES_OPT=-w"
