services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DEFAULT_THEME=dark
    ports:
      - "8071:8081"
    volumes:
      - ${MEDIA_DEFAULT_PATH}/youtube:/downloads