# Jellyfin free media server

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    env_file:
      - .env
    volumes:
      - ${DATA_DEFAULT_PATH}/jellyfin/config:/config
      - ${DATA_DEFAULT_PATH}/jellyfin/cache:/cache
      - type: bind
        source: ${MEDIA_DEFAULT_PATH}/tvshows
        target: /media
      - type: bind
        source: ${MEDIA_DEFAULT_PATH}/movies
        target: /media2
      - type: bind
        source: ${MEDIA_DEFAULT_PATH}/music
        target: /media3
    restart: 'unless-stopped'
    ports:
      - 8097:8096
    #devices:
    #  - /dev/dri:/dev/dri
    # Optional - alternative address used for autodiscovery
    #environment:
      #- JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'